[web]
node1 ansible_host=192.168.1.141 ansible_user=node1 ansible_password=admin
node2 ansible_host=192.168.1.143 ansible_user=node2 ansible_password=admin

[lb]
loadbalancer ansible_host=192.168.1.142 ansible_user=lb ansible_password=admin

[monitor]
grafana ansible_host=192.168.1.147 ansible_user=mon ansible_password=admin
[all:vars]
ansible_connection=ssh
ansible_python_interpreter=/usr/bin/python3
